CREATE TABLE GOODSLIST
   (	
    CATEGORY NUMBER unique, 
	NAME VARCHAR2(30 BYTE) NOT NULL, 
	NUM NUMBER, 
	IMAGE VARCHAR2(2000 BYTE) NOT NULL, 
	TH_IMAGE VARCHAR2(2000 BYTE) NOT NULL, 
	TITLE VARCHAR2(100 BYTE) NOT NULL, 
	CONTEXT1 VARCHAR2(2000 BYTE) NOT NULL, 
	CONTEXT2 VARCHAR2(2000 BYTE) NOT NULL, 
	ISNEW VARCHAR2(5 BYTE)
	)