CREATE TABLE BOARDIR
  (
    BOARD_NUM       NUMBER(*,0),
    BOARD_DATE      DATE,
    BOARD_CONTENT   VARCHAR2(2000 BYTE),
    BOARD_FILE      VARCHAR2(50 BYTE),
    BOARD_Opinion   VARCHAR2(50 BYTE),
    BOARD_Goal      VARCHAR2(50 BYTE),
    BOARD_sources   VARCHAR2(50 BYTE),
    UNIQUE ("BOARD_NUM")

  )